// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_token_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimEmailToken = `-- name: ClaimEmailToken :execrows
UPDATE usr.email_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

// Marks the token used only if nothing has yet. Zero rows means another
// request redeemed it first.
func (q *Queries) ClaimEmailToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimEmailToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO usr.email_tokens (user_id, token, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token, type, expires_at, used_at, created_at
`

type CreateEmailTokenParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	Type      string           `json:"type"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (UsrEmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.UserID,
		arg.Token,
		arg.Type,
		arg.ExpiresAt,
	)
	var i UsrEmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailTokensByUserAndType = `-- name: DeleteEmailTokensByUserAndType :exec
DELETE FROM usr.email_tokens
WHERE user_id = $1 AND type = $2
`

type DeleteEmailTokensByUserAndTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

func (q *Queries) DeleteEmailTokensByUserAndType(ctx context.Context, arg DeleteEmailTokensByUserAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteEmailTokensByUserAndType, arg.UserID, arg.Type)
	return err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :exec
DELETE FROM usr.email_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailTokens)
	return err
}

const getEmailTokenByToken = `-- name: GetEmailTokenByToken :one
SELECT id, user_id, token, type, expires_at, used_at, created_at FROM usr.email_tokens
WHERE token = $1
`

func (q *Queries) GetEmailTokenByToken(ctx context.Context, token string) (UsrEmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByToken, token)
	var i UsrEmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
