// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_delivery_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyEmailDeliveryEvent = `-- name: ApplyEmailDeliveryEvent :execrows
UPDATE usr.email_deliveries
SET status = $2, last_event_at = $3
WHERE provider_message_id = $1
  AND (last_event_at IS NULL OR last_event_at <= $3)
`

type ApplyEmailDeliveryEventParams struct {
	ProviderMessageID string             `json:"provider_message_id"`
	Status            string             `json:"status"`
	LastEventAt       pgtype.Timestamptz `json:"last_event_at"`
}

// ApplyEmailDeliveryEvent is guarded on last_event_at so a webhook that arrives
// late cannot overwrite a newer outcome — Resend retries and does not promise
// ordering, so 'delivered' can land after 'bounced'. Returning the row count is
// what lets the caller tell "no such send" from "stale event, ignored".
func (q *Queries) ApplyEmailDeliveryEvent(ctx context.Context, arg ApplyEmailDeliveryEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyEmailDeliveryEvent, arg.ProviderMessageID, arg.Status, arg.LastEventAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailDelivery = `-- name: CreateEmailDelivery :one
INSERT INTO usr.email_deliveries (user_id, provider_message_id, recipient, kind, status)
VALUES ($1, $2, LOWER($5), $3, $4)
RETURNING id, user_id, provider_message_id, recipient, kind, status, last_event_at, created_at
`

type CreateEmailDeliveryParams struct {
	UserID            uuid.UUID `json:"user_id"`
	ProviderMessageID string    `json:"provider_message_id"`
	Kind              string    `json:"kind"`
	Status            string    `json:"status"`
	Recipient         string    `json:"recipient"`
}

func (q *Queries) CreateEmailDelivery(ctx context.Context, arg CreateEmailDeliveryParams) (UsrEmailDelivery, error) {
	row := q.db.QueryRow(ctx, createEmailDelivery,
		arg.UserID,
		arg.ProviderMessageID,
		arg.Kind,
		arg.Status,
		arg.Recipient,
	)
	var i UsrEmailDelivery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderMessageID,
		&i.Recipient,
		&i.Kind,
		&i.Status,
		&i.LastEventAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailSuppression = `-- name: DeleteEmailSuppression :execrows
DELETE FROM usr.email_suppressions
WHERE email = LOWER($1)
`

func (q *Queries) DeleteEmailSuppression(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailSuppression, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailDeliveryByProviderMessageID = `-- name: GetEmailDeliveryByProviderMessageID :one
SELECT id, user_id, provider_message_id, recipient, kind, status, last_event_at, created_at FROM usr.email_deliveries
WHERE provider_message_id = $1
`

func (q *Queries) GetEmailDeliveryByProviderMessageID(ctx context.Context, providerMessageID string) (UsrEmailDelivery, error) {
	row := q.db.QueryRow(ctx, getEmailDeliveryByProviderMessageID, providerMessageID)
	var i UsrEmailDelivery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderMessageID,
		&i.Recipient,
		&i.Kind,
		&i.Status,
		&i.LastEventAt,
		&i.CreatedAt,
	)
	return i, err
}

const isEmailSuppressed = `-- name: IsEmailSuppressed :one
SELECT EXISTS (
    SELECT 1 FROM usr.email_suppressions WHERE email = LOWER($1)
) AS suppressed
`

func (q *Queries) IsEmailSuppressed(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailSuppressed, email)
	var suppressed bool
	err := row.Scan(&suppressed)
	return suppressed, err
}

const listEmailSuppressions = `-- name: ListEmailSuppressions :many
SELECT email, reason, detail, created_at FROM usr.email_suppressions
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListEmailSuppressions(ctx context.Context, limit int32) ([]UsrEmailSuppression, error) {
	rows, err := q.db.Query(ctx, listEmailSuppressions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrEmailSuppression{}
	for rows.Next() {
		var i UsrEmailSuppression
		if err := rows.Scan(
			&i.Email,
			&i.Reason,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suppressEmail = `-- name: SuppressEmail :exec
INSERT INTO usr.email_suppressions (email, reason, detail)
VALUES (LOWER($3), $1, $2)
ON CONFLICT (email) DO UPDATE
SET reason = EXCLUDED.reason,
    detail = EXCLUDED.detail
`

type SuppressEmailParams struct {
	Reason string  `json:"reason"`
	Detail *string `json:"detail"`
	Email  string  `json:"email"`
}

func (q *Queries) SuppressEmail(ctx context.Context, arg SuppressEmailParams) error {
	_, err := q.db.Exec(ctx, suppressEmail, arg.Reason, arg.Detail, arg.Email)
	return err
}
