// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM usr.follows
WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM usr.follows
WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const follow = `-- name: Follow :exec

INSERT INTO usr.follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

// Follow Queries
func (q *Queries) Follow(ctx context.Context, arg FollowParams) error {
	_, err := q.db.Exec(ctx, follow, arg.FollowerID, arg.FolloweeID)
	return err
}

const getFollowers = `-- name: GetFollowers :many
SELECT follower_id, followee_id, created_at
FROM usr.follows
WHERE followee_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetFollowersParams struct {
	FolloweeID uuid.UUID `json:"followee_id"`
	Offset     int32     `json:"offset"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]UsrFollow, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.FolloweeID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrFollow{}
	for rows.Next() {
		var i UsrFollow
		if err := rows.Scan(&i.FollowerID, &i.FolloweeID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT follower_id, followee_id, created_at
FROM usr.follows
WHERE follower_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Offset     int32     `json:"offset"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]UsrFollow, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.FollowerID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrFollow{}
	for rows.Next() {
		var i UsrFollow
		if err := rows.Scan(&i.FollowerID, &i.FolloweeID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM usr.follows
    WHERE follower_id = $1 AND followee_id = $2
)
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM usr.follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.Exec(ctx, unfollow, arg.FollowerID, arg.FolloweeID)
	return err
}
