// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	// Admin Queries
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]UsrUser, error)
	AdminSetUserActive(ctx context.Context, arg AdminSetUserActiveParams) error
	// User-Role Relationship Queries
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CheckUserHasRole(ctx context.Context, arg CheckUserHasRoleParams) (bool, error)
	CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error)
	CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountSearchUsers(ctx context.Context, query *string) (int64, error)
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (UsrEmailToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UsrRefreshToken, error)
	// Role Queries
	CreateRole(ctx context.Context, arg CreateRoleParams) (UsrRole, error)
	// User Queries
	CreateUser(ctx context.Context, arg CreateUserParams) (UsrUser, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	DeleteEmailTokensByUserAndType(ctx context.Context, arg DeleteEmailTokensByUserAndTypeParams) error
	DeleteExpiredEmailTokens(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	ExistsEmail(ctx context.Context, email string) (bool, error)
	ExistsEmailExcludingUser(ctx context.Context, arg ExistsEmailExcludingUserParams) (bool, error)
	ExistsUsername(ctx context.Context, username string) (bool, error)
	// Follow Queries
	Follow(ctx context.Context, arg FollowParams) error
	GetActiveRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]UsrRefreshToken, error)
	GetEmailTokenByToken(ctx context.Context, token string) (UsrEmailToken, error)
	GetFollowers(ctx context.Context, arg GetFollowersParams) ([]UsrFollow, error)
	GetFollowing(ctx context.Context, arg GetFollowingParams) ([]UsrFollow, error)
	GetRefreshTokenByToken(ctx context.Context, token string) (UsrRefreshToken, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (UsrRole, error)
	GetRoleByName(ctx context.Context, name string) (UsrRole, error)
	GetUserByEmail(ctx context.Context, email string) (UsrUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (UsrUser, error)
	GetUserByIDAny(ctx context.Context, id uuid.UUID) (UsrUser, error)
	GetUserByUsername(ctx context.Context, username string) (UsrUser, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]UsrRole, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UsrUser, error)
	GetUsersByIDsAny(ctx context.Context, dollar_1 []uuid.UUID) ([]UsrUser, error)
	GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]UsrUser, error)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	ListAllActiveUserIDs(ctx context.Context) ([]uuid.UUID, error)
	ListRoles(ctx context.Context) ([]UsrRole, error)
	MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, token string) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]UsrUser, error)
	SearchUsersByQuery(ctx context.Context, arg SearchUsersByQueryParams) ([]UsrUser, error)
	Unfollow(ctx context.Context, arg UnfollowParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UsrUser, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UsrUser, error)
}

var _ Querier = (*Queries)(nil)
