// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	// Admin Queries
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]UsrUser, error)
	AdminSetUserActive(ctx context.Context, arg AdminSetUserActiveParams) error
	// ApplyEmailDeliveryEvent is guarded on last_event_at so a webhook that arrives
	// late cannot overwrite a newer outcome — Resend retries and does not promise
	// ordering, so 'delivered' can land after 'bounced'. Returning the row count is
	// what lets the caller tell "no such send" from "stale event, ignored".
	ApplyEmailDeliveryEvent(ctx context.Context, arg ApplyEmailDeliveryEventParams) (int64, error)
	// User-Role Assignment Queries
	//
	// Role names are stored inline on usr.user_roles and constrained by a CHECK;
	// there is no roles lookup table to join against.
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CheckUserHasAnyRole(ctx context.Context, arg CheckUserHasAnyRoleParams) (bool, error)
	CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error)
	CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error)
	CountSearchUsers(ctx context.Context, query *string) (int64, error)
	CreateEmailDelivery(ctx context.Context, arg CreateEmailDeliveryParams) (UsrEmailDelivery, error)
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (UsrEmailToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UsrRefreshToken, error)
	// User Queries
	CreateUser(ctx context.Context, arg CreateUserParams) (UsrUser, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	DeleteEmailSuppression(ctx context.Context, email string) (int64, error)
	DeleteEmailTokensByUserAndType(ctx context.Context, arg DeleteEmailTokensByUserAndTypeParams) error
	DeleteExpiredEmailTokens(ctx context.Context) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	ExistsEmail(ctx context.Context, email string) (bool, error)
	ExistsEmailExcludingUser(ctx context.Context, arg ExistsEmailExcludingUserParams) (bool, error)
	ExistsUsername(ctx context.Context, username string) (bool, error)
	// Follow Queries
	Follow(ctx context.Context, arg FollowParams) error
	GetActiveRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]UsrRefreshToken, error)
	GetEmailDeliveryByProviderMessageID(ctx context.Context, providerMessageID string) (UsrEmailDelivery, error)
	GetEmailTokenByToken(ctx context.Context, token string) (UsrEmailToken, error)
	GetFollowers(ctx context.Context, arg GetFollowersParams) ([]UsrFollow, error)
	GetFollowing(ctx context.Context, arg GetFollowingParams) ([]UsrFollow, error)
	GetRefreshTokenByToken(ctx context.Context, token string) (UsrRefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (UsrUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (UsrUser, error)
	GetUserByIDAny(ctx context.Context, id uuid.UUID) (UsrUser, error)
	GetUserByUsername(ctx context.Context, username string) (UsrUser, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UsrUser, error)
	GetUsersByIDsAny(ctx context.Context, dollar_1 []uuid.UUID) ([]UsrUser, error)
	GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]UsrUser, error)
	IsEmailSuppressed(ctx context.Context, email string) (bool, error)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	ListAllActiveUserIDs(ctx context.Context) ([]uuid.UUID, error)
	ListEmailSuppressions(ctx context.Context, limit int32) ([]UsrEmailSuppression, error)
	MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, token string) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]UsrUser, error)
	SearchUsersByQuery(ctx context.Context, arg SearchUsersByQueryParams) ([]UsrUser, error)
	SuppressEmail(ctx context.Context, arg SuppressEmailParams) error
	Unfollow(ctx context.Context, arg UnfollowParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UsrUser, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UsrUser, error)
}

var _ Querier = (*Queries)(nil)
