// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE usr.refresh_tokens
SET is_revoked = true, revoked_at = NOW()
WHERE token_hash = $1
  AND is_revoked = false
  AND expires_at > NOW()
RETURNING user_id
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO usr.refresh_tokens (
    token_hash,
    user_id,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, expires_at, created_at, revoked_at, is_revoked, token_hash
`

type CreateRefreshTokenParams struct {
	TokenHash string           `json:"token_hash"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UsrRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i UsrRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsRevoked,
		&i.TokenHash,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM usr.refresh_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getActiveRefreshTokensByUserID = `-- name: GetActiveRefreshTokensByUserID :many
SELECT id, user_id, expires_at, created_at, revoked_at, is_revoked, token_hash FROM usr.refresh_tokens
WHERE user_id = $1 AND is_revoked = false AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]UsrRefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveRefreshTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrRefreshToken{}
	for rows.Next() {
		var i UsrRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.IsRevoked,
			&i.TokenHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, user_id, expires_at, created_at, revoked_at, is_revoked, token_hash FROM usr.refresh_tokens
WHERE token_hash = $1 AND is_revoked = false
LIMIT 1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, tokenHash string) (UsrRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByToken, tokenHash)
	var i UsrRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsRevoked,
		&i.TokenHash,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE usr.refresh_tokens
SET is_revoked = true, revoked_at = NOW()
WHERE user_id = $1 AND is_revoked = false
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE usr.refresh_tokens
SET is_revoked = true, revoked_at = NOW()
WHERE token_hash = $1 AND is_revoked = false
RETURNING id
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, tokenHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
