// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO usr.refresh_tokens (
    token,
    user_id,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, token, user_id, expires_at, created_at, revoked_at, is_revoked
`

type CreateRefreshTokenParams struct {
	Token     string           `json:"token"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UsrRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i UsrRefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsRevoked,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM usr.refresh_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getActiveRefreshTokensByUserID = `-- name: GetActiveRefreshTokensByUserID :many
SELECT id, token, user_id, expires_at, created_at, revoked_at, is_revoked FROM usr.refresh_tokens
WHERE user_id = $1 AND is_revoked = false AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]UsrRefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveRefreshTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrRefreshToken{}
	for rows.Next() {
		var i UsrRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.IsRevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, token, user_id, expires_at, created_at, revoked_at, is_revoked FROM usr.refresh_tokens
WHERE token = $1 AND is_revoked = false
LIMIT 1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (UsrRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByToken, token)
	var i UsrRefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsRevoked,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE usr.refresh_tokens
SET is_revoked = true, revoked_at = NOW()
WHERE user_id = $1 AND is_revoked = false
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE usr.refresh_tokens
SET is_revoked = true, revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}
