// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*) FROM usr.users
WHERE (
    $1::boolean IS NULL OR is_active = $1::boolean
  )
  AND (
    $2::text IS NULL
    OR $2::text = ''
    OR username     ILIKE '%' || $2::text || '%'
    OR email        ILIKE '%' || $2::text || '%'
    OR display_name ILIKE '%' || $2::text || '%'
  )
`

type AdminCountUsersParams struct {
	IsActive *bool   `json:"is_active"`
	Query    *string `json:"query"`
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.IsActive, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE (
    $1::boolean IS NULL OR is_active = $1::boolean
  )
  AND (
    $2::text IS NULL
    OR $2::text = ''
    OR username     ILIKE '%' || $2::text || '%'
    OR email        ILIKE '%' || $2::text || '%'
    OR display_name ILIKE '%' || $2::text || '%'
  )
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type AdminListUsersParams struct {
	IsActive *bool   `json:"is_active"`
	Query    *string `json:"query"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

// Admin Queries
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]UsrUser, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.IsActive,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrUser{}
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarKey,
			&i.CoverKey,
			&i.Website,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FollowerCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserActive = `-- name: AdminSetUserActive :exec
UPDATE usr.users
SET is_active  = $2,
    updated_at = NOW(),
    updated_by = $3
WHERE id = $1
`

type AdminSetUserActiveParams struct {
	ID        uuid.UUID   `json:"id"`
	IsActive  bool        `json:"is_active"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) AdminSetUserActive(ctx context.Context, arg AdminSetUserActiveParams) error {
	_, err := q.db.Exec(ctx, adminSetUserActive, arg.ID, arg.IsActive, arg.UpdatedBy)
	return err
}

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*) FROM usr.users
WHERE is_active = true
  AND (
    $1::text IS NULL
    OR $1::text = ''
    OR username ILIKE '%' || $1::text || '%'
    OR email    ILIKE '%' || $1::text || '%'
  )
`

func (q *Queries) CountSearchUsers(ctx context.Context, query *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO usr.users (
    username,
    email,
    password_hash,
    display_name,
    created_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

// User Queries
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UsrUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.CreatedBy,
	)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE usr.users
SET
    is_active  = false,
    updated_at = NOW(),
    updated_by = $2
WHERE id = $1
`

type DeactivateUserParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.Exec(ctx, deactivateUser, arg.ID, arg.UpdatedBy)
	return err
}

const existsEmail = `-- name: ExistsEmail :one
SELECT EXISTS(
    SELECT 1 FROM usr.users
    WHERE email = $1
)
`

func (q *Queries) ExistsEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsEmailExcludingUser = `-- name: ExistsEmailExcludingUser :one
SELECT EXISTS(
    SELECT 1 FROM usr.users
    WHERE email = $1 AND id != $2
)
`

type ExistsEmailExcludingUserParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) ExistsEmailExcludingUser(ctx context.Context, arg ExistsEmailExcludingUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsEmailExcludingUser, arg.Email, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUsername = `-- name: ExistsUsername :one
SELECT EXISTS(
    SELECT 1 FROM usr.users
    WHERE username = $1
)
`

func (q *Queries) ExistsUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE email = $1 AND is_active = true
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UsrUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (UsrUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}

const getUserByIDAny = `-- name: GetUserByIDAny :one
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE id = $1
`

func (q *Queries) GetUserByIDAny(ctx context.Context, id uuid.UUID) (UsrUser, error) {
	row := q.db.QueryRow(ctx, getUserByIDAny, id)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE username = $1 AND is_active = true
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (UsrUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE id = ANY($1::uuid[])
  AND is_active = true
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UsrUser, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrUser{}
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarKey,
			&i.CoverKey,
			&i.Website,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FollowerCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIDsAny = `-- name: GetUsersByIDsAny :many
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetUsersByIDsAny(ctx context.Context, dollar_1 []uuid.UUID) ([]UsrUser, error) {
	rows, err := q.db.Query(ctx, getUsersByIDsAny, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrUser{}
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarKey,
			&i.CoverKey,
			&i.Website,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FollowerCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByUsernames = `-- name: GetUsersByUsernames :many
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE username = ANY($1::text[])
  AND is_active = true
`

func (q *Queries) GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]UsrUser, error) {
	rows, err := q.db.Query(ctx, getUsersByUsernames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrUser{}
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarKey,
			&i.CoverKey,
			&i.Website,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FollowerCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveUserIDs = `-- name: ListAllActiveUserIDs :many
SELECT id FROM usr.users WHERE is_active = true ORDER BY created_at ASC
`

func (q *Queries) ListAllActiveUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAllActiveUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE is_active = true
  AND (
    $3::text IS NULL
    OR $3::text = ''
    OR username ILIKE '%' || $3::text || '%'
    OR email    ILIKE '%' || $3::text || '%'
  )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchUsersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Query  *string `json:"query"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]UsrUser, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrUser{}
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarKey,
			&i.CoverKey,
			&i.Website,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FollowerCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByQuery = `-- name: SearchUsersByQuery :many
SELECT id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count FROM usr.users
WHERE is_active = true
  AND (
    username     ILIKE '%' || $1::text || '%'
    OR display_name ILIKE '%' || $1::text || '%'
  )
ORDER BY
  CASE WHEN username ILIKE $1::text || '%' THEN 0 ELSE 1 END,
  follower_count DESC
LIMIT $3 OFFSET $2
`

type SearchUsersByQueryParams struct {
	Query  string `json:"query"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) SearchUsersByQuery(ctx context.Context, arg SearchUsersByQueryParams) ([]UsrUser, error) {
	rows, err := q.db.Query(ctx, searchUsersByQuery, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsrUser{}
	for rows.Next() {
		var i UsrUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarKey,
			&i.CoverKey,
			&i.Website,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FollowerCount,
			&i.FollowingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE usr.users
SET
    email      = COALESCE($1, email),
    updated_at = NOW(),
    updated_by = $2
WHERE id = $3
RETURNING id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count
`

type UpdateUserParams struct {
	Email     *string     `json:"email"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UsrUser, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Email, arg.UpdatedBy, arg.ID)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE usr.users
SET
    password_hash = $2,
    updated_at    = NOW(),
    updated_by    = $3
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash string      `json:"password_hash"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedBy)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE usr.users
SET
    display_name = COALESCE($1, display_name),
    bio          = COALESCE($2, bio),
    avatar_key   = COALESCE($3, avatar_key),
    cover_key    = COALESCE($4, cover_key),
    website      = COALESCE($5, website),
    location     = COALESCE($6, location),
    updated_at   = NOW()
WHERE id = $7
RETURNING id, username, email, password_hash, is_active, display_name, bio, avatar_key, cover_key, website, location, created_at, updated_at, created_by, updated_by, follower_count, following_count
`

type UpdateUserProfileParams struct {
	DisplayName *string   `json:"display_name"`
	Bio         *string   `json:"bio"`
	AvatarKey   *string   `json:"avatar_key"`
	CoverKey    *string   `json:"cover_key"`
	Website     *string   `json:"website"`
	Location    *string   `json:"location"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UsrUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarKey,
		arg.CoverKey,
		arg.Website,
		arg.Location,
		arg.ID,
	)
	var i UsrUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarKey,
		&i.CoverKey,
		&i.Website,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FollowerCount,
		&i.FollowingCount,
	)
	return i, err
}
