// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SettingsFeed struct {
	ID                     int16              `json:"id"`
	TimelineEnabled        bool               `json:"timeline_enabled"`
	TimelineRolloutPercent int16              `json:"timeline_rollout_percent"`
	TimelineMaxItems       int32              `json:"timeline_max_items"`
	TimelineTtlSeconds     int32              `json:"timeline_ttl_seconds"`
	TimelineRefreshOnMiss  bool               `json:"timeline_refresh_on_miss"`
	FanoutEnabled          bool               `json:"fanout_enabled"`
	FanoutMaxFollowers     int32              `json:"fanout_max_followers"`
	RelationshipBonus      float64            `json:"relationship_bonus"`
	RecencyScale           float64            `json:"recency_scale"`
	DecayExponent          float64            `json:"decay_exponent"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}
