// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// ─── Feed settings ───────────────────────────────────────────────────────────
	//
	// The row is created by the migration, so both queries assume id = 1 exists.
	// There is no upsert-on-read: a missing row would be a second "no value" case the
	// refresher would have to tell apart from a failed query, and the column defaults
	// already answer both.
	GetFeedSettings(ctx context.Context) (SettingsFeed, error)
	// Partial update: every settable column is COALESCE'd against its own value, so a
	// NULL parameter means "unchanged" rather than "clear". That is what lets the
	// admin API accept a body naming one knob without the caller having to read the
	// other nine and send them back — a read-modify-write that would lose a
	// concurrent edit made between the two calls.
	//
	// updated_by is deliberately not COALESCE'd, for the same reason as
	// UpdateBotConfig: it records who saved last, so a caller that omits it must not
	// leave the previous editor's name attached to someone else's change. The service
	// is the only writer and always passes the acting admin.
	UpdateFeedSettings(ctx context.Context, arg UpdateFeedSettingsParams) (SettingsFeed, error)
}

var _ Querier = (*Queries)(nil)
