// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFeedSettings = `-- name: GetFeedSettings :one

SELECT id, timeline_enabled, timeline_rollout_percent, timeline_max_items, timeline_ttl_seconds, timeline_refresh_on_miss, fanout_enabled, fanout_max_followers, relationship_bonus, recency_scale, decay_exponent, updated_by, updated_at FROM settings.feed WHERE id = 1
`

// ─── Feed settings ───────────────────────────────────────────────────────────
//
// The row is created by the migration, so both queries assume id = 1 exists.
// There is no upsert-on-read: a missing row would be a second "no value" case the
// refresher would have to tell apart from a failed query, and the column defaults
// already answer both.
func (q *Queries) GetFeedSettings(ctx context.Context) (SettingsFeed, error) {
	row := q.db.QueryRow(ctx, getFeedSettings)
	var i SettingsFeed
	err := row.Scan(
		&i.ID,
		&i.TimelineEnabled,
		&i.TimelineRolloutPercent,
		&i.TimelineMaxItems,
		&i.TimelineTtlSeconds,
		&i.TimelineRefreshOnMiss,
		&i.FanoutEnabled,
		&i.FanoutMaxFollowers,
		&i.RelationshipBonus,
		&i.RecencyScale,
		&i.DecayExponent,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeedSettings = `-- name: UpdateFeedSettings :one
UPDATE settings.feed
SET timeline_enabled         = COALESCE($1, timeline_enabled),
    timeline_rollout_percent = COALESCE($2, timeline_rollout_percent),
    timeline_max_items       = COALESCE($3, timeline_max_items),
    timeline_ttl_seconds     = COALESCE($4, timeline_ttl_seconds),
    timeline_refresh_on_miss = COALESCE($5, timeline_refresh_on_miss),
    fanout_enabled           = COALESCE($6, fanout_enabled),
    fanout_max_followers     = COALESCE($7, fanout_max_followers),
    relationship_bonus       = COALESCE($8, relationship_bonus),
    recency_scale            = COALESCE($9, recency_scale),
    decay_exponent           = COALESCE($10, decay_exponent),
    updated_by               = $11,
    updated_at               = NOW()
WHERE id = 1
RETURNING id, timeline_enabled, timeline_rollout_percent, timeline_max_items, timeline_ttl_seconds, timeline_refresh_on_miss, fanout_enabled, fanout_max_followers, relationship_bonus, recency_scale, decay_exponent, updated_by, updated_at
`

type UpdateFeedSettingsParams struct {
	TimelineEnabled        *bool       `json:"timeline_enabled"`
	TimelineRolloutPercent *int16      `json:"timeline_rollout_percent"`
	TimelineMaxItems       *int32      `json:"timeline_max_items"`
	TimelineTtlSeconds     *int32      `json:"timeline_ttl_seconds"`
	TimelineRefreshOnMiss  *bool       `json:"timeline_refresh_on_miss"`
	FanoutEnabled          *bool       `json:"fanout_enabled"`
	FanoutMaxFollowers     *int32      `json:"fanout_max_followers"`
	RelationshipBonus      *float64    `json:"relationship_bonus"`
	RecencyScale           *float64    `json:"recency_scale"`
	DecayExponent          *float64    `json:"decay_exponent"`
	UpdatedBy              pgtype.UUID `json:"updated_by"`
}

// Partial update: every settable column is COALESCE'd against its own value, so a
// NULL parameter means "unchanged" rather than "clear". That is what lets the
// admin API accept a body naming one knob without the caller having to read the
// other nine and send them back — a read-modify-write that would lose a
// concurrent edit made between the two calls.
//
// updated_by is deliberately not COALESCE'd, for the same reason as
// UpdateBotConfig: it records who saved last, so a caller that omits it must not
// leave the previous editor's name attached to someone else's change. The service
// is the only writer and always passes the acting admin.
func (q *Queries) UpdateFeedSettings(ctx context.Context, arg UpdateFeedSettingsParams) (SettingsFeed, error) {
	row := q.db.QueryRow(ctx, updateFeedSettings,
		arg.TimelineEnabled,
		arg.TimelineRolloutPercent,
		arg.TimelineMaxItems,
		arg.TimelineTtlSeconds,
		arg.TimelineRefreshOnMiss,
		arg.FanoutEnabled,
		arg.FanoutMaxFollowers,
		arg.RelationshipBonus,
		arg.RecencyScale,
		arg.DecayExponent,
		arg.UpdatedBy,
	)
	var i SettingsFeed
	err := row.Scan(
		&i.ID,
		&i.TimelineEnabled,
		&i.TimelineRolloutPercent,
		&i.TimelineMaxItems,
		&i.TimelineTtlSeconds,
		&i.TimelineRefreshOnMiss,
		&i.FanoutEnabled,
		&i.FanoutMaxFollowers,
		&i.RelationshipBonus,
		&i.RecencyScale,
		&i.DecayExponent,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
