// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearBotRunRequest = `-- name: ClearBotRunRequest :exec
UPDATE bot.bots SET run_requested_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ClearBotRunRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearBotRunRequest, id)
	return err
}

const countRuns = `-- name: CountRuns :one
SELECT COUNT(*) FROM bot.runs
WHERE ($1::uuid IS NULL OR bot_id = $1::uuid)
`

func (q *Queries) CountRuns(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRuns, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBot = `-- name: CreateBot :one
INSERT INTO bot.bots (username, display_name, style)
VALUES ($1, $2, $3)
RETURNING id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at
`

type CreateBotParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Style       string `json:"style"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (BotBot, error) {
	row := q.db.QueryRow(ctx, createBot, arg.Username, arg.DisplayName, arg.Style)
	var i BotBot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Style,
		&i.Enabled,
		&i.UserID,
		&i.RunRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one

INSERT INTO bot.runs (bot_id, post_id, model_used, status, error)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bot_id, post_id, model_used, status, error, created_at
`

type CreateRunParams struct {
	BotID     uuid.UUID   `json:"bot_id"`
	PostID    pgtype.UUID `json:"post_id"`
	ModelUsed *string     `json:"model_used"`
	Status    string      `json:"status"`
	Error     *string     `json:"error"`
}

// ─── Activity log ────────────────────────────────────────────────────────────
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (BotRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.BotID,
		arg.PostID,
		arg.ModelUsed,
		arg.Status,
		arg.Error,
	)
	var i BotRun
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.PostID,
		&i.ModelUsed,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO bot.topics (content) VALUES ($1) RETURNING id, content, enabled, created_at
`

func (q *Queries) CreateTopic(ctx context.Context, content string) (BotTopic, error) {
	row := q.db.QueryRow(ctx, createTopic, content)
	var i BotTopic
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBot = `-- name: DeleteBot :exec
DELETE FROM bot.bots WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBot, id)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM bot.topics WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getBot = `-- name: GetBot :one
SELECT id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at FROM bot.bots WHERE id = $1
`

func (q *Queries) GetBot(ctx context.Context, id uuid.UUID) (BotBot, error) {
	row := q.db.QueryRow(ctx, getBot, id)
	var i BotBot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Style,
		&i.Enabled,
		&i.UserID,
		&i.RunRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotByUsername = `-- name: GetBotByUsername :one
SELECT id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at FROM bot.bots WHERE username = $1
`

func (q *Queries) GetBotByUsername(ctx context.Context, username string) (BotBot, error) {
	row := q.db.QueryRow(ctx, getBotByUsername, username)
	var i BotBot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Style,
		&i.Enabled,
		&i.UserID,
		&i.RunRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotConfig = `-- name: GetBotConfig :one

SELECT id, post_interval_seconds, accounts, models, paused, updated_by, updated_at FROM bot.config WHERE id = 1
`

// ─── Config ──────────────────────────────────────────────────────────────────
func (q *Queries) GetBotConfig(ctx context.Context) (BotConfig, error) {
	row := q.db.QueryRow(ctx, getBotConfig)
	var i BotConfig
	err := row.Scan(
		&i.ID,
		&i.PostIntervalSeconds,
		&i.Accounts,
		&i.Models,
		&i.Paused,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const linkBotUser = `-- name: LinkBotUser :exec
UPDATE bot.bots SET user_id = $2, updated_at = NOW() WHERE id = $1
`

type LinkBotUserParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Called by the bot once it has registered or logged in the account, so the admin
// view can link a persona to the user it posts as.
func (q *Queries) LinkBotUser(ctx context.Context, arg LinkBotUserParams) error {
	_, err := q.db.Exec(ctx, linkBotUser, arg.ID, arg.UserID)
	return err
}

const listBotRunStats = `-- name: ListBotRunStats :many
SELECT bot_id,
       (MAX(created_at) FILTER (WHERE status = 'success'))::timestamptz       AS last_success_at,
       (MAX(created_at) FILTER (WHERE status = 'error'))::timestamptz         AS last_error_at,
       COUNT(*) FILTER (WHERE status = 'success'
                          AND created_at >= NOW() - INTERVAL '24 hours')      AS successes_last_24h,
       COUNT(*) FILTER (WHERE status = 'error'
                          AND created_at >= NOW() - INTERVAL '24 hours')      AS errors_last_24h
FROM bot.runs
WHERE created_at >= $1
GROUP BY bot_id
`

type ListBotRunStatsRow struct {
	BotID            uuid.UUID          `json:"bot_id"`
	LastSuccessAt    pgtype.Timestamptz `json:"last_success_at"`
	LastErrorAt      pgtype.Timestamptz `json:"last_error_at"`
	SuccessesLast24h int64              `json:"successes_last_24h"`
	ErrorsLast24h    int64              `json:"errors_last_24h"`
}

// Per-persona summary for the status columns of GET /admin/bots. Aggregating in
// one pass avoids a query per bot in the list handler.
//
// The cutoff is the same retention window the prune uses, so the summary can never
// describe a period the log no longer covers. It also keeps this bounded if pruning
// ever stops — a persona that has gone quiet stops reporting, and with it stops
// triggering the prune.
//
// Driving this from bot.bots with a subquery per persona looks like it should be
// faster and measurably is not: with no rows for a persona the planner walks the
// whole created_at index looking for a match that never comes. Measured at 210k
// rows, that shape took 250ms against 45ms for this one. The scan is the right
// answer; bounding what it scans is the fix.
//
// The MAX casts are load-bearing: sqlc cannot infer the type of an aggregate with
// a FILTER clause and emits interface{} without them, pushing a runtime type
// assertion into the repository.
func (q *Queries) ListBotRunStats(ctx context.Context, retentionCutoff pgtype.Timestamptz) ([]ListBotRunStatsRow, error) {
	rows, err := q.db.Query(ctx, listBotRunStats, retentionCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBotRunStatsRow{}
	for rows.Next() {
		var i ListBotRunStatsRow
		if err := rows.Scan(
			&i.BotID,
			&i.LastSuccessAt,
			&i.LastErrorAt,
			&i.SuccessesLast24h,
			&i.ErrorsLast24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBots = `-- name: ListBots :many

SELECT id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at FROM bot.bots ORDER BY username
`

// ─── Personas ────────────────────────────────────────────────────────────────
func (q *Queries) ListBots(ctx context.Context) ([]BotBot, error) {
	rows, err := q.db.Query(ctx, listBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotBot{}
	for rows.Next() {
		var i BotBot
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Style,
			&i.Enabled,
			&i.UserID,
			&i.RunRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledBots = `-- name: ListEnabledBots :many
SELECT id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at FROM bot.bots
WHERE enabled
ORDER BY (run_requested_at IS NULL), username
LIMIT $1
`

// Serves GET /bot/plan. The limit is bot.config.accounts, and ordering by username
// keeps the selection stable so a config change is the only thing that moves it.
//
// Personas with a pending run request sort first, which is load-bearing rather than
// cosmetic: an operator can ask any persona to post now, but the plan only carries
// `accounts` of them. Without this, a request for a persona sorting past the cap
// would sit in the table forever and run-now would silently do nothing.
func (q *Queries) ListEnabledBots(ctx context.Context, limit int32) ([]BotBot, error) {
	rows, err := q.db.Query(ctx, listEnabledBots, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotBot{}
	for rows.Next() {
		var i BotBot
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Style,
			&i.Enabled,
			&i.UserID,
			&i.RunRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTopics = `-- name: ListEnabledTopics :many
SELECT id, content, enabled, created_at FROM bot.topics WHERE enabled ORDER BY created_at, content
`

func (q *Queries) ListEnabledTopics(ctx context.Context) ([]BotTopic, error) {
	rows, err := q.db.Query(ctx, listEnabledTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotTopic{}
	for rows.Next() {
		var i BotTopic
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, bot_id, post_id, model_used, status, error, created_at FROM bot.runs
WHERE ($1::uuid IS NULL OR bot_id = $1::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListRunsParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

// A NULL bot_id means "every bot", so one query serves both the global log and a
// single persona's history.
func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]BotRun, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.BotID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotRun{}
	for rows.Next() {
		var i BotRun
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.PostID,
			&i.ModelUsed,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many

SELECT id, content, enabled, created_at FROM bot.topics ORDER BY created_at, content
`

// ─── Topics ──────────────────────────────────────────────────────────────────
// content breaks the created_at tie: the seeded rows all share one timestamp, so
// created_at alone leaves the admin list in arbitrary order.
func (q *Queries) ListTopics(ctx context.Context) ([]BotTopic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BotTopic{}
	for rows.Next() {
		var i BotTopic
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRuns = `-- name: PruneRuns :execrows
DELETE FROM bot.runs WHERE created_at < $1
`

// Drops runs past the retention window, keeping the log — and therefore the cost of
// summarising it below — bounded however long the bot runs. Called on each report
// rather than by a scheduler: in steady state the index finds nothing to delete and
// it costs well under a millisecond, which is cheaper than owning a cron.
func (q *Queries) PruneRuns(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRuns, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestBotRun = `-- name: RequestBotRun :one

UPDATE bot.bots SET run_requested_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at
`

// ─── Run-now flag ────────────────────────────────────────────────────────────
func (q *Queries) RequestBotRun(ctx context.Context, id uuid.UUID) (BotBot, error) {
	row := q.db.QueryRow(ctx, requestBotRun, id)
	var i BotBot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Style,
		&i.Enabled,
		&i.UserID,
		&i.RunRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTopicEnabled = `-- name: SetTopicEnabled :one
UPDATE bot.topics SET enabled = $2 WHERE id = $1 RETURNING id, content, enabled, created_at
`

type SetTopicEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetTopicEnabled(ctx context.Context, arg SetTopicEnabledParams) (BotTopic, error) {
	row := q.db.QueryRow(ctx, setTopicEnabled, arg.ID, arg.Enabled)
	var i BotTopic
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateBot = `-- name: UpdateBot :one
UPDATE bot.bots
SET display_name     = COALESCE($1, display_name),
    style            = COALESCE($2, style),
    enabled          = COALESCE($3, enabled),
    run_requested_at = CASE
                           WHEN COALESCE($3, enabled) THEN run_requested_at
                           ELSE NULL
                       END,
    updated_at       = NOW()
WHERE id = $4
RETURNING id, username, display_name, style, enabled, user_id, run_requested_at, created_at, updated_at
`

type UpdateBotParams struct {
	DisplayName *string   `json:"display_name"`
	Style       *string   `json:"style"`
	Enabled     *bool     `json:"enabled"`
	ID          uuid.UUID `json:"id"`
}

// COALESCE over nullable args makes this a partial update: an omitted field keeps
// its stored value rather than being cleared.
//
// Disabling a persona also retires any pending run-now. The plan only carries
// enabled personas, so the request can no longer fire; leaving it set would make
// the persona post the instant someone re-enables it, answering a request made
// however long ago. Done in the same statement so there is no window where a
// disabled persona still looks like it has a run pending.
func (q *Queries) UpdateBot(ctx context.Context, arg UpdateBotParams) (BotBot, error) {
	row := q.db.QueryRow(ctx, updateBot,
		arg.DisplayName,
		arg.Style,
		arg.Enabled,
		arg.ID,
	)
	var i BotBot
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Style,
		&i.Enabled,
		&i.UserID,
		&i.RunRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotConfig = `-- name: UpdateBotConfig :one
UPDATE bot.config
SET post_interval_seconds = COALESCE($1, post_interval_seconds),
    accounts              = COALESCE($2, accounts),
    models                = COALESCE($3, models),
    paused                = COALESCE($4, paused),
    updated_by            = $5,
    updated_at            = NOW()
WHERE id = 1
RETURNING id, post_interval_seconds, accounts, models, paused, updated_by, updated_at
`

type UpdateBotConfigParams struct {
	PostIntervalSeconds *int32      `json:"post_interval_seconds"`
	Accounts            *int16      `json:"accounts"`
	Models              []string    `json:"models"`
	Paused              *bool       `json:"paused"`
	UpdatedBy           pgtype.UUID `json:"updated_by"`
}

// Every editable field is COALESCE'd so an omitted one keeps its stored value.
//
// updated_by deliberately is not. It records who saved last, so it has to be
// overwritten on every write — wrapping it in COALESCE would make a caller that
// omits it silently leave the previous editor's name against someone else's change,
// which is worse than recording nobody. Every caller does supply it; the service is
// the only writer and always passes the acting admin.
func (q *Queries) UpdateBotConfig(ctx context.Context, arg UpdateBotConfigParams) (BotConfig, error) {
	row := q.db.QueryRow(ctx, updateBotConfig,
		arg.PostIntervalSeconds,
		arg.Accounts,
		arg.Models,
		arg.Paused,
		arg.UpdatedBy,
	)
	var i BotConfig
	err := row.Scan(
		&i.ID,
		&i.PostIntervalSeconds,
		&i.Accounts,
		&i.Models,
		&i.Paused,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
