// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BotBot struct {
	ID             uuid.UUID          `json:"id"`
	Username       string             `json:"username"`
	DisplayName    string             `json:"display_name"`
	Style          string             `json:"style"`
	Enabled        bool               `json:"enabled"`
	UserID         pgtype.UUID        `json:"user_id"`
	RunRequestedAt pgtype.Timestamptz `json:"run_requested_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type BotConfig struct {
	ID                   int16              `json:"id"`
	PostIntervalSeconds  int32              `json:"post_interval_seconds"`
	Accounts             int16              `json:"accounts"`
	Models               []string           `json:"models"`
	Paused               bool               `json:"paused"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	PromptTemplate       string             `json:"prompt_template"`
	Temperature          float64            `json:"temperature"`
	MaxTagsPerPost       int16              `json:"max_tags_per_post"`
	RecentMemory         int16              `json:"recent_memory"`
	ApiTimeoutSeconds    int16              `json:"api_timeout_seconds"`
	GeminiTimeoutSeconds int16              `json:"gemini_timeout_seconds"`
}

type BotRun struct {
	ID        uuid.UUID          `json:"id"`
	BotID     uuid.UUID          `json:"bot_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	ModelUsed *string            `json:"model_used"`
	Status    string             `json:"status"`
	Error     *string            `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BotTopic struct {
	ID        uuid.UUID          `json:"id"`
	Content   string             `json:"content"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
