// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearBotRunRequest(ctx context.Context, id uuid.UUID) error
	CountRuns(ctx context.Context, botID pgtype.UUID) (int64, error)
	CreateBot(ctx context.Context, arg CreateBotParams) (BotBot, error)
	// ─── Activity log ────────────────────────────────────────────────────────────
	CreateRun(ctx context.Context, arg CreateRunParams) (BotRun, error)
	CreateTopic(ctx context.Context, content string) (BotTopic, error)
	DeleteBot(ctx context.Context, id uuid.UUID) error
	DeleteTopic(ctx context.Context, id uuid.UUID) error
	GetBot(ctx context.Context, id uuid.UUID) (BotBot, error)
	GetBotByUsername(ctx context.Context, username string) (BotBot, error)
	// ─── Config ──────────────────────────────────────────────────────────────────
	GetBotConfig(ctx context.Context) (BotConfig, error)
	GetLastBotError(ctx context.Context, botID uuid.UUID) (BotRun, error)
	// Called by the bot once it has registered or logged in the account, so the admin
	// view can link a persona to the user it posts as.
	LinkBotUser(ctx context.Context, arg LinkBotUserParams) error
	// Per-persona summary for the status columns of GET /admin/bots. Aggregating in
	// one pass avoids a query per bot in the list handler.
	ListBotRunStats(ctx context.Context) ([]ListBotRunStatsRow, error)
	// ─── Personas ────────────────────────────────────────────────────────────────
	ListBots(ctx context.Context) ([]BotBot, error)
	// Serves GET /bot/plan. The limit is bot.config.accounts; ordering by username
	// keeps the selection stable so a config change is the only thing that moves it.
	ListEnabledBots(ctx context.Context, limit int32) ([]BotBot, error)
	ListEnabledTopics(ctx context.Context) ([]BotTopic, error)
	// A NULL bot_id means "every bot", so one query serves both the global log and a
	// single persona's history.
	ListRuns(ctx context.Context, arg ListRunsParams) ([]BotRun, error)
	// ─── Topics ──────────────────────────────────────────────────────────────────
	// content breaks the created_at tie: the seeded rows all share one timestamp, so
	// created_at alone leaves the admin list in arbitrary order.
	ListTopics(ctx context.Context) ([]BotTopic, error)
	// ─── Run-now flag ────────────────────────────────────────────────────────────
	RequestBotRun(ctx context.Context, id uuid.UUID) (BotBot, error)
	SetTopicEnabled(ctx context.Context, arg SetTopicEnabledParams) (BotTopic, error)
	// COALESCE over nullable args makes this a partial update: an omitted field keeps
	// its stored value rather than being cleared.
	UpdateBot(ctx context.Context, arg UpdateBotParams) (BotBot, error)
	UpdateBotConfig(ctx context.Context, arg UpdateBotConfigParams) (BotConfig, error)
}

var _ Querier = (*Queries)(nil)
