// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearBotRunRequest(ctx context.Context, id uuid.UUID) error
	CountRuns(ctx context.Context, botID pgtype.UUID) (int64, error)
	CreateBot(ctx context.Context, arg CreateBotParams) (BotBot, error)
	// ─── Activity log ────────────────────────────────────────────────────────────
	CreateRun(ctx context.Context, arg CreateRunParams) (BotRun, error)
	CreateTopic(ctx context.Context, content string) (BotTopic, error)
	DeleteBot(ctx context.Context, id uuid.UUID) error
	DeleteTopic(ctx context.Context, id uuid.UUID) error
	GetBot(ctx context.Context, id uuid.UUID) (BotBot, error)
	GetBotByUsername(ctx context.Context, username string) (BotBot, error)
	// ─── Config ──────────────────────────────────────────────────────────────────
	GetBotConfig(ctx context.Context) (BotConfig, error)
	// Called by the bot once it has registered or logged in the account, so the admin
	// view can link a persona to the user it posts as.
	LinkBotUser(ctx context.Context, arg LinkBotUserParams) error
	// Per-persona summary for the status columns of GET /admin/bots. Aggregating in
	// one pass avoids a query per bot in the list handler.
	// The MAX casts are load-bearing: sqlc cannot infer the type of an aggregate with
	// a FILTER clause and emits interface{} without them, pushing a runtime type
	// assertion into the repository.
	ListBotRunStats(ctx context.Context) ([]ListBotRunStatsRow, error)
	// ─── Personas ────────────────────────────────────────────────────────────────
	ListBots(ctx context.Context) ([]BotBot, error)
	// Serves GET /bot/plan. The limit is bot.config.accounts, and ordering by username
	// keeps the selection stable so a config change is the only thing that moves it.
	//
	// Personas with a pending run request sort first, which is load-bearing rather than
	// cosmetic: an operator can ask any persona to post now, but the plan only carries
	// `accounts` of them. Without this, a request for a persona sorting past the cap
	// would sit in the table forever and run-now would silently do nothing.
	ListEnabledBots(ctx context.Context, limit int32) ([]BotBot, error)
	ListEnabledTopics(ctx context.Context) ([]BotTopic, error)
	// A NULL bot_id means "every bot", so one query serves both the global log and a
	// single persona's history.
	ListRuns(ctx context.Context, arg ListRunsParams) ([]BotRun, error)
	// ─── Topics ──────────────────────────────────────────────────────────────────
	// content breaks the created_at tie: the seeded rows all share one timestamp, so
	// created_at alone leaves the admin list in arbitrary order.
	ListTopics(ctx context.Context) ([]BotTopic, error)
	// ─── Run-now flag ────────────────────────────────────────────────────────────
	RequestBotRun(ctx context.Context, id uuid.UUID) (BotBot, error)
	SetTopicEnabled(ctx context.Context, arg SetTopicEnabledParams) (BotTopic, error)
	// COALESCE over nullable args makes this a partial update: an omitted field keeps
	// its stored value rather than being cleared.
	//
	// Disabling a persona also retires any pending run-now. The plan only carries
	// enabled personas, so the request can no longer fire; leaving it set would make
	// the persona post the instant someone re-enables it, answering a request made
	// however long ago. Done in the same statement so there is no window where a
	// disabled persona still looks like it has a run pending.
	UpdateBot(ctx context.Context, arg UpdateBotParams) (BotBot, error)
	UpdateBotConfig(ctx context.Context, arg UpdateBotConfigParams) (BotConfig, error)
}

var _ Querier = (*Queries)(nil)
