// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_like_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLikedCommentIDs = `-- name: GetLikedCommentIDs :many
SELECT comment_id FROM post.comment_likes
WHERE user_id = $1
  AND comment_id = ANY($2::uuid[])
`

type GetLikedCommentIDsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) GetLikedCommentIDs(ctx context.Context, arg GetLikedCommentIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getLikedCommentIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var comment_id uuid.UUID
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isCommentLiked = `-- name: IsCommentLiked :one
SELECT EXISTS(
    SELECT 1 FROM post.comment_likes
    WHERE user_id = $1 AND comment_id = $2
)
`

type IsCommentLikedParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CommentID uuid.UUID `json:"comment_id"`
}

func (q *Queries) IsCommentLiked(ctx context.Context, arg IsCommentLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCommentLiked, arg.UserID, arg.CommentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likeComment = `-- name: LikeComment :exec
INSERT INTO post.comment_likes (user_id, comment_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikeCommentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CommentID uuid.UUID `json:"comment_id"`
}

func (q *Queries) LikeComment(ctx context.Context, arg LikeCommentParams) error {
	_, err := q.db.Exec(ctx, likeComment, arg.UserID, arg.CommentID)
	return err
}

const unlikeComment = `-- name: UnlikeComment :exec
DELETE FROM post.comment_likes
WHERE user_id = $1 AND comment_id = $2
`

type UnlikeCommentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CommentID uuid.UUID `json:"comment_id"`
}

func (q *Queries) UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeComment, arg.UserID, arg.CommentID)
	return err
}
