// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_media_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCommentMedia = `-- name: AddCommentMedia :one
INSERT INTO post.comment_media (comment_id, media_key, media_type, position)
VALUES ($1, $2, $3, $4)
RETURNING id, comment_id, media_key, media_type, position, created_at
`

type AddCommentMediaParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	MediaKey  string    `json:"media_key"`
	MediaType string    `json:"media_type"`
	Position  int32     `json:"position"`
}

func (q *Queries) AddCommentMedia(ctx context.Context, arg AddCommentMediaParams) (PostCommentMedium, error) {
	row := q.db.QueryRow(ctx, addCommentMedia,
		arg.CommentID,
		arg.MediaKey,
		arg.MediaType,
		arg.Position,
	)
	var i PostCommentMedium
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.MediaKey,
		&i.MediaType,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllCommentMedia = `-- name: DeleteAllCommentMedia :exec
DELETE FROM post.comment_media
WHERE comment_id = $1
`

func (q *Queries) DeleteAllCommentMedia(ctx context.Context, commentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllCommentMedia, commentID)
	return err
}

const getCommentMedia = `-- name: GetCommentMedia :many
SELECT id, comment_id, media_key, media_type, position, created_at FROM post.comment_media
WHERE comment_id = $1
ORDER BY position ASC
`

func (q *Queries) GetCommentMedia(ctx context.Context, commentID uuid.UUID) ([]PostCommentMedium, error) {
	rows, err := q.db.Query(ctx, getCommentMedia, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostCommentMedium{}
	for rows.Next() {
		var i PostCommentMedium
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.MediaKey,
			&i.MediaType,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentMediaBatch = `-- name: GetCommentMediaBatch :many
SELECT id, comment_id, media_key, media_type, position, created_at FROM post.comment_media
WHERE comment_id = ANY($1::uuid[])
ORDER BY comment_id, position ASC
`

func (q *Queries) GetCommentMediaBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]PostCommentMedium, error) {
	rows, err := q.db.Query(ctx, getCommentMediaBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostCommentMedium{}
	for rows.Next() {
		var i PostCommentMedium
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.MediaKey,
			&i.MediaType,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
