// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPost = `-- name: CountCommentsByPost :one
SELECT COUNT(*) FROM post.comments
WHERE post_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountCommentsByPost(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPost, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO post.comments (post_id, author_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, author_id, parent_id, content, created_at, updated_at, deleted_at, like_count
`

type CreateCommentParams struct {
	PostID   uuid.UUID   `json:"post_id"`
	AuthorID uuid.UUID   `json:"author_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Content  string      `json:"content"`
}

// Comment Queries
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (PostComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
	)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LikeCount,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE post.comments
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, author_id, parent_id, content, created_at, updated_at, deleted_at, like_count FROM post.comments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (PostComment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LikeCount,
	)
	return i, err
}

const getCommentsByPost = `-- name: GetCommentsByPost :many
SELECT id, post_id, author_id, parent_id, content, created_at, updated_at, deleted_at, like_count FROM post.comments
WHERE post_id = $1
  AND parent_id IS NULL
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type GetCommentsByPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	Offset int32     `json:"offset"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetCommentsByPost(ctx context.Context, arg GetCommentsByPostParams) ([]PostComment, error) {
	rows, err := q.db.Query(ctx, getCommentsByPost, arg.PostID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostComment{}
	for rows.Next() {
		var i PostComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplies = `-- name: GetReplies :many
SELECT id, post_id, author_id, parent_id, content, created_at, updated_at, deleted_at, like_count FROM post.comments
WHERE parent_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type GetRepliesParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) GetReplies(ctx context.Context, arg GetRepliesParams) ([]PostComment, error) {
	rows, err := q.db.Query(ctx, getReplies, arg.ParentID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostComment{}
	for rows.Next() {
		var i PostComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepliesPreview = `-- name: GetRepliesPreview :many
SELECT id, post_id, author_id, parent_id, content, created_at, updated_at, deleted_at, like_count
FROM (
    SELECT id, post_id, author_id, parent_id, content, created_at, updated_at, deleted_at, like_count,
           ROW_NUMBER() OVER (PARTITION BY parent_id ORDER BY created_at ASC) AS rn
    FROM post.comments
    WHERE parent_id = ANY($1::uuid[])
      AND deleted_at IS NULL
) ranked
WHERE rn <= $2::int
ORDER BY parent_id, created_at ASC
`

type GetRepliesPreviewParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 int32       `json:"column_2"`
}

func (q *Queries) GetRepliesPreview(ctx context.Context, arg GetRepliesPreviewParams) ([]PostComment, error) {
	rows, err := q.db.Query(ctx, getRepliesPreview, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostComment{}
	for rows.Next() {
		var i PostComment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplyCountsBatch = `-- name: GetReplyCountsBatch :many
SELECT parent_id AS root_id, COUNT(*) AS count
FROM post.comments
WHERE parent_id = ANY($1::uuid[])
  AND deleted_at IS NULL
GROUP BY parent_id
`

type GetReplyCountsBatchRow struct {
	RootID pgtype.UUID `json:"root_id"`
	Count  int64       `json:"count"`
}

func (q *Queries) GetReplyCountsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]GetReplyCountsBatchRow, error) {
	rows, err := q.db.Query(ctx, getReplyCountsBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReplyCountsBatchRow{}
	for rows.Next() {
		var i GetReplyCountsBatchRow
		if err := rows.Scan(&i.RootID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
