// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_mention_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteCommentMentionsByComment = `-- name: DeleteCommentMentionsByComment :exec
DELETE FROM post.comment_mentions WHERE comment_id = $1
`

func (q *Queries) DeleteCommentMentionsByComment(ctx context.Context, commentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentMentionsByComment, commentID)
	return err
}

const getCommentMentionsBatch = `-- name: GetCommentMentionsBatch :many
SELECT comment_id, user_id, created_at FROM post.comment_mentions WHERE comment_id = ANY($1::uuid[])
`

func (q *Queries) GetCommentMentionsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]PostCommentMention, error) {
	rows, err := q.db.Query(ctx, getCommentMentionsBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostCommentMention{}
	for rows.Next() {
		var i PostCommentMention
		if err := rows.Scan(&i.CommentID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentMentionsByComment = `-- name: GetCommentMentionsByComment :many
SELECT comment_id, user_id, created_at FROM post.comment_mentions WHERE comment_id = $1
`

func (q *Queries) GetCommentMentionsByComment(ctx context.Context, commentID uuid.UUID) ([]PostCommentMention, error) {
	rows, err := q.db.Query(ctx, getCommentMentionsByComment, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostCommentMention{}
	for rows.Next() {
		var i PostCommentMention
		if err := rows.Scan(&i.CommentID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommentMention = `-- name: InsertCommentMention :exec
INSERT INTO post.comment_mentions (comment_id, user_id)
VALUES ($1, $2)
ON CONFLICT (comment_id, user_id) DO NOTHING
`

type InsertCommentMentionParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertCommentMention(ctx context.Context, arg InsertCommentMentionParams) error {
	_, err := q.db.Exec(ctx, insertCommentMention, arg.CommentID, arg.UserID)
	return err
}
