// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hashtag_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePostHashtags = `-- name: DeletePostHashtags :exec

DELETE FROM post.post_hashtags WHERE post_id = $1
`

// Hand-patched batch queries (sqlc cannot generate unnest-based batch inserts):
//
// UpsertHashtagsBatch: batch upsert hashtag names, returns all upserted rows
//
//	INSERT INTO post.hashtags (name) SELECT unnest($1::text[])
//	ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
//	RETURNING id, name, created_at
//
// LinkPostHashtagsBatch: link a post to multiple hashtag IDs in one statement
//
//	INSERT INTO post.post_hashtags (post_id, hashtag_id)
//	SELECT $1::uuid, unnest($2::uuid[])
//	ON CONFLICT DO NOTHING
func (q *Queries) DeletePostHashtags(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePostHashtags, postID)
	return err
}

const getHashtagsByPostID = `-- name: GetHashtagsByPostID :many
SELECT h.id, h.name, h.created_at
FROM post.hashtags h
JOIN post.post_hashtags ph ON ph.hashtag_id = h.id
WHERE ph.post_id = $1
ORDER BY h.name
`

func (q *Queries) GetHashtagsByPostID(ctx context.Context, postID uuid.UUID) ([]PostHashtag, error) {
	rows, err := q.db.Query(ctx, getHashtagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostHashtag{}
	for rows.Next() {
		var i PostHashtag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHashtagsByPostIDs = `-- name: GetHashtagsByPostIDs :many
SELECT ph.post_id, h.name
FROM post.hashtags h
JOIN post.post_hashtags ph ON ph.hashtag_id = h.id
WHERE ph.post_id = ANY($1::uuid[])
ORDER BY ph.post_id, h.name
`

type GetHashtagsByPostIDsRow struct {
	PostID uuid.UUID `json:"post_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetHashtagsByPostIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetHashtagsByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, getHashtagsByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHashtagsByPostIDsRow{}
	for rows.Next() {
		var i GetHashtagsByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByHashtagWithCursor = `-- name: GetPostsByHashtagWithCursor :many
SELECT p.id, p.author_id, p.content, p.visibility, p.created_at, p.updated_at, p.deleted_at, p.like_count, p.comment_count
FROM post.posts p
JOIN post.post_hashtags ph ON ph.post_id   = p.id
JOIN post.hashtags      h  ON h.id         = ph.hashtag_id
WHERE h.name         = $1
  AND p.visibility   = 'public'
  AND p.deleted_at   IS NULL
  AND (p.created_at < $2::timestamptz
       OR (p.created_at = $2::timestamptz AND p.id < $3::uuid))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4
`

type GetPostsByHashtagWithCursorParams struct {
	Name    string             `json:"name"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 uuid.UUID          `json:"column_3"`
	Limit   int32              `json:"limit"`
}

type GetPostsByHashtagWithCursorRow struct {
	ID           uuid.UUID          `json:"id"`
	AuthorID     uuid.UUID          `json:"author_id"`
	Content      string             `json:"content"`
	Visibility   string             `json:"visibility"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
}

func (q *Queries) GetPostsByHashtagWithCursor(ctx context.Context, arg GetPostsByHashtagWithCursorParams) ([]GetPostsByHashtagWithCursorRow, error) {
	rows, err := q.db.Query(ctx, getPostsByHashtagWithCursor,
		arg.Name,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByHashtagWithCursorRow{}
	for rows.Next() {
		var i GetPostsByHashtagWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrendingHashtags = `-- name: GetTrendingHashtags :many
SELECT h.name, COUNT(*) AS count
FROM post.post_hashtags ph
JOIN post.hashtags h  ON h.id  = ph.hashtag_id
JOIN post.posts    p  ON p.id  = ph.post_id
WHERE p.created_at > NOW() - INTERVAL '24 hours'
  AND p.visibility = 'public'
  AND p.deleted_at IS NULL
GROUP BY h.id, h.name
ORDER BY count DESC
LIMIT $1
`

type GetTrendingHashtagsRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetTrendingHashtags(ctx context.Context, limit int32) ([]GetTrendingHashtagsRow, error) {
	rows, err := q.db.Query(ctx, getTrendingHashtags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTrendingHashtagsRow{}
	for rows.Next() {
		var i GetTrendingHashtagsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkPostHashtag = `-- name: LinkPostHashtag :exec
INSERT INTO post.post_hashtags (post_id, hashtag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkPostHashtagParams struct {
	PostID    uuid.UUID `json:"post_id"`
	HashtagID uuid.UUID `json:"hashtag_id"`
}

func (q *Queries) LinkPostHashtag(ctx context.Context, arg LinkPostHashtagParams) error {
	_, err := q.db.Exec(ctx, linkPostHashtag, arg.PostID, arg.HashtagID)
	return err
}

const searchHashtagsByPrefix = `-- name: SearchHashtagsByPrefix :many
SELECT name
FROM post.hashtags
WHERE name LIKE $1::text || '%'
ORDER BY name
LIMIT $2
`

type SearchHashtagsByPrefixParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) SearchHashtagsByPrefix(ctx context.Context, arg SearchHashtagsByPrefixParams) ([]string, error) {
	rows, err := q.db.Query(ctx, searchHashtagsByPrefix, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHashtag = `-- name: UpsertHashtag :one
INSERT INTO post.hashtags (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertHashtag(ctx context.Context, name string) (PostHashtag, error) {
	row := q.db.QueryRow(ctx, upsertHashtag, name)
	var i PostHashtag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
