// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: like_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countLikes = `-- name: CountLikes :one
SELECT COUNT(*) FROM post.likes
WHERE post_id = $1
`

func (q *Queries) CountLikes(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikes, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLikedPostIDs = `-- name: GetLikedPostIDs :many
SELECT post_id FROM post.likes
WHERE user_id = $1
  AND post_id = ANY($2::uuid[])
`

type GetLikedPostIDsParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) GetLikedPostIDs(ctx context.Context, arg GetLikedPostIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getLikedPostIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var post_id uuid.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isLiked = `-- name: IsLiked :one
SELECT EXISTS(
    SELECT 1 FROM post.likes
    WHERE user_id = $1 AND post_id = $2
)
`

type IsLikedParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) IsLiked(ctx context.Context, arg IsLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isLiked, arg.UserID, arg.PostID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likePost = `-- name: LikePost :exec

INSERT INTO post.likes (user_id, post_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikePostParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

// Like Queries
func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.Exec(ctx, likePost, arg.UserID, arg.PostID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM post.likes
WHERE user_id = $1 AND post_id = $2
`

type UnlikePostParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.Exec(ctx, unlikePost, arg.UserID, arg.PostID)
	return err
}
