// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPostMedia = `-- name: AddPostMedia :one

INSERT INTO post.post_media (post_id, media_key, media_type, position)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, media_key, media_type, position, created_at
`

type AddPostMediaParams struct {
	PostID    uuid.UUID `json:"post_id"`
	MediaKey  string    `json:"media_key"`
	MediaType string    `json:"media_type"`
	Position  int32     `json:"position"`
}

// Post Media Queries
func (q *Queries) AddPostMedia(ctx context.Context, arg AddPostMediaParams) (PostPostMedium, error) {
	row := q.db.QueryRow(ctx, addPostMedia,
		arg.PostID,
		arg.MediaKey,
		arg.MediaType,
		arg.Position,
	)
	var i PostPostMedium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.MediaKey,
		&i.MediaType,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllPostMedia = `-- name: DeleteAllPostMedia :exec
DELETE FROM post.post_media
WHERE post_id = $1
`

func (q *Queries) DeleteAllPostMedia(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllPostMedia, postID)
	return err
}

const deletePostMedia = `-- name: DeletePostMedia :exec
DELETE FROM post.post_media
WHERE id = $1 AND post_id = $2
`

type DeletePostMediaParams struct {
	ID     uuid.UUID `json:"id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) DeletePostMedia(ctx context.Context, arg DeletePostMediaParams) error {
	_, err := q.db.Exec(ctx, deletePostMedia, arg.ID, arg.PostID)
	return err
}

const getPostMedia = `-- name: GetPostMedia :many
SELECT id, post_id, media_key, media_type, position, created_at FROM post.post_media
WHERE post_id = $1
ORDER BY position ASC
`

func (q *Queries) GetPostMedia(ctx context.Context, postID uuid.UUID) ([]PostPostMedium, error) {
	rows, err := q.db.Query(ctx, getPostMedia, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPostMedium{}
	for rows.Next() {
		var i PostPostMedium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.MediaKey,
			&i.MediaType,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
