// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mention_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteMentionsByPost = `-- name: DeleteMentionsByPost :exec
DELETE FROM post.post_mentions WHERE post_id = $1
`

func (q *Queries) DeleteMentionsByPost(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMentionsByPost, postID)
	return err
}

const getMentionsBatch = `-- name: GetMentionsBatch :many
SELECT post_id, user_id, created_at FROM post.post_mentions WHERE post_id = ANY($1::uuid[])
`

func (q *Queries) GetMentionsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]PostPostMention, error) {
	rows, err := q.db.Query(ctx, getMentionsBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPostMention{}
	for rows.Next() {
		var i PostPostMention
		if err := rows.Scan(&i.PostID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMentionsByPost = `-- name: GetMentionsByPost :many
SELECT post_id, user_id, created_at FROM post.post_mentions WHERE post_id = $1
`

func (q *Queries) GetMentionsByPost(ctx context.Context, postID uuid.UUID) ([]PostPostMention, error) {
	rows, err := q.db.Query(ctx, getMentionsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPostMention{}
	for rows.Next() {
		var i PostPostMention
		if err := rows.Scan(&i.PostID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMention = `-- name: InsertMention :exec
INSERT INTO post.post_mentions (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type InsertMentionParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertMention(ctx context.Context, arg InsertMentionParams) error {
	_, err := q.db.Exec(ctx, insertMention, arg.PostID, arg.UserID)
	return err
}
