// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PostComment struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"post_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	LikeCount int64              `json:"like_count"`
}

type PostCommentMedium struct {
	ID        uuid.UUID          `json:"id"`
	CommentID uuid.UUID          `json:"comment_id"`
	MediaKey  string             `json:"media_key"`
	MediaType string             `json:"media_type"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostCommentMention struct {
	CommentID uuid.UUID          `json:"comment_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostHashtag struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostPost struct {
	ID           uuid.UUID          `json:"id"`
	AuthorID     uuid.UUID          `json:"author_id"`
	Content      string             `json:"content"`
	Visibility   string             `json:"visibility"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
	SearchVector interface{}        `json:"search_vector"`
}

type PostPostMedium struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"post_id"`
	MediaKey  string             `json:"media_key"`
	MediaType string             `json:"media_type"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostPostMention struct {
	PostID    uuid.UUID          `json:"post_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
