// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDiscoverPosts = `-- name: CountDiscoverPosts :one
SELECT COUNT(*) FROM post.posts
WHERE deleted_at IS NULL
  AND visibility = 'public'
`

func (q *Queries) CountDiscoverPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDiscoverPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeedPosts = `-- name: CountFeedPosts :one
SELECT COUNT(*) FROM post.posts
WHERE author_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND visibility IN ('public', 'followers')
`

func (q *Queries) CountFeedPosts(ctx context.Context, authorIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFeedPosts, authorIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByAuthor = `-- name: CountPostsByAuthor :one
SELECT COUNT(*) FROM post.posts
WHERE author_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPostsByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByAuthor, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one

INSERT INTO post.posts (author_id, content, visibility)
VALUES ($1, $2, $3)
RETURNING id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector
`

type CreatePostParams struct {
	AuthorID   uuid.UUID `json:"author_id"`
	Content    string    `json:"content"`
	Visibility string    `json:"visibility"`
}

// Post Queries
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (PostPost, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Content, arg.Visibility)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LikeCount,
		&i.CommentCount,
		&i.SearchVector,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
UPDATE post.posts
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getDiscoverPosts = `-- name: GetDiscoverPosts :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE deleted_at IS NULL
  AND visibility = 'public'
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetDiscoverPostsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetDiscoverPosts(ctx context.Context, arg GetDiscoverPostsParams) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getDiscoverPosts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscoverWithCursor = `-- name: GetDiscoverWithCursor :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE deleted_at IS NULL
  AND visibility = 'public'
  AND (created_at, id) < ($1::timestamptz, $2::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type GetDiscoverWithCursorParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorPostID    uuid.UUID          `json:"cursor_post_id"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) GetDiscoverWithCursor(ctx context.Context, arg GetDiscoverWithCursorParams) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getDiscoverWithCursor, arg.CursorCreatedAt, arg.CursorPostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedPosts = `-- name: GetFeedPosts :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE author_id = ANY($1::uuid[])
  AND deleted_at IS NULL
  AND visibility IN ('public', 'followers')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetFeedPostsParams struct {
	AuthorIds []uuid.UUID `json:"author_ids"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getFeedPosts, arg.AuthorIds, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingPosts = `-- name: GetFollowingPosts :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE author_id = ANY($1::uuid[])
  AND created_at > NOW() - INTERVAL '7 days'
  AND visibility IN ('public', 'followers')
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GetFollowingPostsParams struct {
	AuthorIds []uuid.UUID `json:"author_ids"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetFollowingPosts(ctx context.Context, arg GetFollowingPostsParams) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getFollowingPosts, arg.AuthorIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingPostsWithCursor = `-- name: GetFollowingPostsWithCursor :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count
FROM post.posts
WHERE author_id = ANY($1::uuid[])
  AND visibility = 'public'
  AND deleted_at IS NULL
  AND (created_at < $2::timestamptz
       OR (created_at = $2::timestamptz AND id < $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type GetFollowingPostsWithCursorParams struct {
	Column1 []uuid.UUID        `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 uuid.UUID          `json:"column_3"`
	Limit   int32              `json:"limit"`
}

type GetFollowingPostsWithCursorRow struct {
	ID           uuid.UUID          `json:"id"`
	AuthorID     uuid.UUID          `json:"author_id"`
	Content      string             `json:"content"`
	Visibility   string             `json:"visibility"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
}

func (q *Queries) GetFollowingPostsWithCursor(ctx context.Context, arg GetFollowingPostsWithCursorParams) ([]GetFollowingPostsWithCursorRow, error) {
	rows, err := q.db.Query(ctx, getFollowingPostsWithCursor,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingPostsWithCursorRow{}
	for rows.Next() {
		var i GetFollowingPostsWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (PostPost, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LikeCount,
		&i.CommentCount,
		&i.SearchVector,
	)
	return i, err
}

const getPostsByAuthor = `-- name: GetPostsByAuthor :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE author_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetPostsByAuthorParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) GetPostsByAuthor(ctx context.Context, arg GetPostsByAuthorParams) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getPostsByAuthor, arg.AuthorID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrendingPosts = `-- name: GetTrendingPosts :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE created_at > NOW() - INTERVAL '24 hours'
  AND visibility = 'public'
  AND deleted_at IS NULL
ORDER BY like_count DESC
LIMIT $1
`

func (q *Queries) GetTrendingPosts(ctx context.Context, limit int32) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getTrendingPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPostsWithCursor = `-- name: GetUserPostsWithCursor :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector FROM post.posts
WHERE author_id = $1
  AND deleted_at IS NULL
  AND ($4::text = '' OR visibility = $4::text)
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type GetUserPostsWithCursorParams struct {
	AuthorID uuid.UUID          `json:"author_id"`
	Column2  pgtype.Timestamptz `json:"column_2"`
	Column3  uuid.UUID          `json:"column_3"`
	Column4  string             `json:"column_4"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) GetUserPostsWithCursor(ctx context.Context, arg GetUserPostsWithCursorParams) ([]PostPost, error) {
	rows, err := q.db.Query(ctx, getUserPostsWithCursor,
		arg.AuthorID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostPost{}
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE post.posts
SET content = $2, visibility = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count, search_vector
`

type UpdatePostParams struct {
	ID         uuid.UUID `json:"id"`
	Content    string    `json:"content"`
	Visibility string    `json:"visibility"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (PostPost, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.ID, arg.Content, arg.Visibility)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Content,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LikeCount,
		&i.CommentCount,
		&i.SearchVector,
	)
	return i, err
}
