// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCommentMedia(ctx context.Context, arg AddCommentMediaParams) (PostCommentMedium, error)
	// Post Media Queries
	AddPostMedia(ctx context.Context, arg AddPostMediaParams) (PostPostMedium, error)
	CountCommentsByPost(ctx context.Context, postID uuid.UUID) (int64, error)
	CountDiscoverPosts(ctx context.Context) (int64, error)
	CountFeedPosts(ctx context.Context, authorIds []uuid.UUID) (int64, error)
	CountLikes(ctx context.Context, postID uuid.UUID) (int64, error)
	CountPostsByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error)
	// Comment Queries
	CreateComment(ctx context.Context, arg CreateCommentParams) (PostComment, error)
	// Post Queries
	CreatePost(ctx context.Context, arg CreatePostParams) (PostPost, error)
	DeleteAllCommentMedia(ctx context.Context, commentID uuid.UUID) error
	DeleteAllPostMedia(ctx context.Context, postID uuid.UUID) error
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteCommentMentionsByComment(ctx context.Context, commentID uuid.UUID) error
	DeleteMentionsByPost(ctx context.Context, postID uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	// Hand-patched batch queries (sqlc cannot generate unnest-based batch inserts):
	//
	// UpsertHashtagsBatch: batch upsert hashtag names, returns all upserted rows
	//   INSERT INTO post.hashtags (name) SELECT unnest($1::text[])
	//   ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
	//   RETURNING id, name, created_at
	//
	// LinkPostHashtagsBatch: link a post to multiple hashtag IDs in one statement
	//   INSERT INTO post.post_hashtags (post_id, hashtag_id)
	//   SELECT $1::uuid, unnest($2::uuid[])
	//   ON CONFLICT DO NOTHING
	DeletePostHashtags(ctx context.Context, postID uuid.UUID) error
	DeletePostMedia(ctx context.Context, arg DeletePostMediaParams) error
	GetCommentByID(ctx context.Context, id uuid.UUID) (PostComment, error)
	GetCommentMedia(ctx context.Context, commentID uuid.UUID) ([]PostCommentMedium, error)
	GetCommentMediaBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]PostCommentMedium, error)
	GetCommentMentionsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]PostCommentMention, error)
	GetCommentMentionsByComment(ctx context.Context, commentID uuid.UUID) ([]PostCommentMention, error)
	GetCommentsByPost(ctx context.Context, arg GetCommentsByPostParams) ([]PostComment, error)
	GetDiscoverPosts(ctx context.Context, arg GetDiscoverPostsParams) ([]PostPost, error)
	GetDiscoverWithCursor(ctx context.Context, arg GetDiscoverWithCursorParams) ([]PostPost, error)
	GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]PostPost, error)
	GetFollowingPosts(ctx context.Context, arg GetFollowingPostsParams) ([]PostPost, error)
	GetFollowingPostsWithCursor(ctx context.Context, arg GetFollowingPostsWithCursorParams) ([]GetFollowingPostsWithCursorRow, error)
	GetHashtagsByPostID(ctx context.Context, postID uuid.UUID) ([]PostHashtag, error)
	GetHashtagsByPostIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetHashtagsByPostIDsRow, error)
	GetLikedCommentIDs(ctx context.Context, arg GetLikedCommentIDsParams) ([]uuid.UUID, error)
	GetLikedPostIDs(ctx context.Context, arg GetLikedPostIDsParams) ([]uuid.UUID, error)
	GetMentionsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]PostPostMention, error)
	GetMentionsByPost(ctx context.Context, postID uuid.UUID) ([]PostPostMention, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (PostPost, error)
	GetPostMedia(ctx context.Context, postID uuid.UUID) ([]PostPostMedium, error)
	GetPostsByAuthor(ctx context.Context, arg GetPostsByAuthorParams) ([]PostPost, error)
	GetPostsByHashtagWithCursor(ctx context.Context, arg GetPostsByHashtagWithCursorParams) ([]GetPostsByHashtagWithCursorRow, error)
	GetReplies(ctx context.Context, arg GetRepliesParams) ([]PostComment, error)
	GetRepliesPreview(ctx context.Context, arg GetRepliesPreviewParams) ([]PostComment, error)
	GetReplyCountsBatch(ctx context.Context, dollar_1 []uuid.UUID) ([]GetReplyCountsBatchRow, error)
	GetTrendingHashtags(ctx context.Context, limit int32) ([]GetTrendingHashtagsRow, error)
	GetTrendingPosts(ctx context.Context, limit int32) ([]PostPost, error)
	GetUserPostsWithCursor(ctx context.Context, arg GetUserPostsWithCursorParams) ([]PostPost, error)
	InsertCommentMention(ctx context.Context, arg InsertCommentMentionParams) error
	InsertMention(ctx context.Context, arg InsertMentionParams) error
	IsCommentLiked(ctx context.Context, arg IsCommentLikedParams) (bool, error)
	IsLiked(ctx context.Context, arg IsLikedParams) (bool, error)
	LikeComment(ctx context.Context, arg LikeCommentParams) error
	// Like Queries
	LikePost(ctx context.Context, arg LikePostParams) error
	LinkPostHashtag(ctx context.Context, arg LinkPostHashtagParams) error
	SearchHashtagsByPrefix(ctx context.Context, arg SearchHashtagsByPrefixParams) ([]string, error)
	UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error
	UnlikePost(ctx context.Context, arg UnlikePostParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (PostPost, error)
	UpsertHashtag(ctx context.Context, name string) (PostHashtag, error)
}

var _ Querier = (*Queries)(nil)
