// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchPosts = `-- name: SearchPosts :many
SELECT id, author_id, content, visibility, created_at, updated_at, deleted_at, like_count, comment_count
FROM post.posts
WHERE deleted_at IS NULL
  AND visibility = 'public'
  AND search_vector @@ plainto_tsquery('english', $1::text)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $1::text)) DESC, created_at DESC
LIMIT $3 OFFSET $2
`

type SearchPostsParams struct {
	Query  string `json:"query"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

type SearchPostsRow struct {
	ID           uuid.UUID          `json:"id"`
	AuthorID     uuid.UUID          `json:"author_id"`
	Content      string             `json:"content"`
	Visibility   string             `json:"visibility"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	LikeCount    int64              `json:"like_count"`
	CommentCount int64              `json:"comment_count"`
}

// SearchPosts performs a full-text search over public posts using tsvector.
func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Content,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LikeCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
