// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationNotification struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	ActorID     uuid.UUID          `json:"actor_id"`
	Type        string             `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	SecondaryID pgtype.UUID        `json:"secondary_id"`
	GroupKey    string             `json:"group_key"`
	IsRead      bool               `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Message     *string            `json:"message"`
}

type UsrEmailDelivery struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	ProviderMessageID string             `json:"provider_message_id"`
	Recipient         string             `json:"recipient"`
	Kind              string             `json:"kind"`
	Status            string             `json:"status"`
	LastEventAt       pgtype.Timestamptz `json:"last_event_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UsrEmailSuppression struct {
	Email     string             `json:"email"`
	Reason    string             `json:"reason"`
	Detail    *string            `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UsrEmailToken struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	Type      string           `json:"type"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UsedAt    pgtype.Timestamp `json:"used_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type UsrFollow struct {
	FollowerID uuid.UUID          `json:"follower_id"`
	FolloweeID uuid.UUID          `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UsrRefreshToken struct {
	ID        uuid.UUID        `json:"id"`
	Token     string           `json:"token"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
	IsRevoked bool             `json:"is_revoked"`
}

type UsrUser struct {
	ID             uuid.UUID        `json:"id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	PasswordHash   string           `json:"password_hash"`
	IsActive       bool             `json:"is_active"`
	DisplayName    string           `json:"display_name"`
	Bio            *string          `json:"bio"`
	AvatarKey      *string          `json:"avatar_key"`
	CoverKey       *string          `json:"cover_key"`
	Website        *string          `json:"website"`
	Location       *string          `json:"location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CreatedBy      pgtype.UUID      `json:"created_by"`
	UpdatedBy      pgtype.UUID      `json:"updated_by"`
	FollowerCount  int64            `json:"follower_count"`
	FollowingCount int64            `json:"following_count"`
}

type UsrUserRole struct {
	UserID     uuid.UUID        `json:"user_id"`
	AssignedAt pgtype.Timestamp `json:"assigned_at"`
	AssignedBy pgtype.UUID      `json:"assigned_by"`
	Role       string           `json:"role"`
}
