// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnread = `-- name: CountUnread :one
SELECT COUNT(*)
FROM notification.notifications
WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnread(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notification.notifications (recipient_id, actor_id, type, target_id, secondary_id, group_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (recipient_id, actor_id, type, group_key)
DO UPDATE SET created_at = NOW(), is_read = FALSE
RETURNING id, recipient_id, actor_id, type, target_id, secondary_id, group_key, is_read, created_at
`

type CreateNotificationParams struct {
	RecipientID uuid.UUID   `json:"recipient_id"`
	ActorID     uuid.UUID   `json:"actor_id"`
	Type        string      `json:"type"`
	TargetID    pgtype.UUID `json:"target_id"`
	SecondaryID pgtype.UUID `json:"secondary_id"`
	GroupKey    string      `json:"group_key"`
}

type CreateNotificationRow struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	ActorID     uuid.UUID          `json:"actor_id"`
	Type        string             `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	SecondaryID pgtype.UUID        `json:"secondary_id"`
	GroupKey    string             `json:"group_key"`
	IsRead      bool               `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.Type,
		arg.TargetID,
		arg.SecondaryID,
		arg.GroupKey,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.TargetID,
		&i.SecondaryID,
		&i.GroupKey,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const createSystemNotification = `-- name: CreateSystemNotification :one
INSERT INTO notification.notifications (recipient_id, actor_id, type, group_key, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, recipient_id, actor_id, type, target_id, secondary_id, group_key, is_read, created_at, message
`

type CreateSystemNotificationParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	ActorID     uuid.UUID `json:"actor_id"`
	Type        string    `json:"type"`
	GroupKey    string    `json:"group_key"`
	Message     *string   `json:"message"`
}

func (q *Queries) CreateSystemNotification(ctx context.Context, arg CreateSystemNotificationParams) (NotificationNotification, error) {
	row := q.db.QueryRow(ctx, createSystemNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.Type,
		arg.GroupKey,
		arg.Message,
	)
	var i NotificationNotification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.TargetID,
		&i.SecondaryID,
		&i.GroupKey,
		&i.IsRead,
		&i.CreatedAt,
		&i.Message,
	)
	return i, err
}

const deleteByActorAndGroupKey = `-- name: DeleteByActorAndGroupKey :exec
DELETE FROM notification.notifications
WHERE actor_id = $1 AND group_key = $2
`

type DeleteByActorAndGroupKeyParams struct {
	ActorID  uuid.UUID `json:"actor_id"`
	GroupKey string    `json:"group_key"`
}

func (q *Queries) DeleteByActorAndGroupKey(ctx context.Context, arg DeleteByActorAndGroupKeyParams) error {
	_, err := q.db.Exec(ctx, deleteByActorAndGroupKey, arg.ActorID, arg.GroupKey)
	return err
}

const getGroupActors = `-- name: GetGroupActors :many
SELECT actor_id, COUNT(*) OVER() AS total_count
FROM notification.notifications
WHERE recipient_id = $1 AND group_key = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetGroupActorsParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	GroupKey    string    `json:"group_key"`
	Limit       int32     `json:"limit"`
}

type GetGroupActorsRow struct {
	ActorID    uuid.UUID `json:"actor_id"`
	TotalCount int64     `json:"total_count"`
}

func (q *Queries) GetGroupActors(ctx context.Context, arg GetGroupActorsParams) ([]GetGroupActorsRow, error) {
	rows, err := q.db.Query(ctx, getGroupActors, arg.RecipientID, arg.GroupKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupActorsRow{}
	for rows.Next() {
		var i GetGroupActorsRow
		if err := rows.Scan(&i.ActorID, &i.TotalCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsWithCursor = `-- name: GetNotificationsWithCursor :many
SELECT id, recipient_id, actor_id, type, target_id, secondary_id, group_key, is_read, created_at
FROM notification.notifications
WHERE recipient_id = $1
  AND (
      created_at < $2::timestamptz
      OR (created_at = $2::timestamptz AND id < $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type GetNotificationsWithCursorParams struct {
	RecipientID uuid.UUID          `json:"recipient_id"`
	Column2     pgtype.Timestamptz `json:"column_2"`
	Column3     uuid.UUID          `json:"column_3"`
	Limit       int32              `json:"limit"`
}

type GetNotificationsWithCursorRow struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	ActorID     uuid.UUID          `json:"actor_id"`
	Type        string             `json:"type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	SecondaryID pgtype.UUID        `json:"secondary_id"`
	GroupKey    string             `json:"group_key"`
	IsRead      bool               `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetNotificationsWithCursor(ctx context.Context, arg GetNotificationsWithCursorParams) ([]GetNotificationsWithCursorRow, error) {
	rows, err := q.db.Query(ctx, getNotificationsWithCursor,
		arg.RecipientID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNotificationsWithCursorRow{}
	for rows.Next() {
		var i GetNotificationsWithCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.Type,
			&i.TargetID,
			&i.SecondaryID,
			&i.GroupKey,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsRead = `-- name: MarkAllAsRead :exec
UPDATE notification.notifications
SET is_read = TRUE
WHERE recipient_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllAsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllAsRead, recipientID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notification.notifications
SET is_read = TRUE
WHERE id = $1 AND recipient_id = $2 AND is_read = FALSE
`

type MarkAsReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.RecipientID)
	return err
}
