// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUnread(ctx context.Context, recipientID uuid.UUID) (int64, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	CreateSystemNotification(ctx context.Context, arg CreateSystemNotificationParams) (NotificationNotification, error)
	DeleteByActorAndGroupKey(ctx context.Context, arg DeleteByActorAndGroupKeyParams) error
	GetGroupActors(ctx context.Context, arg GetGroupActorsParams) ([]GetGroupActorsRow, error)
	GetNotificationsWithCursor(ctx context.Context, arg GetNotificationsWithCursorParams) ([]GetNotificationsWithCursorRow, error)
	MarkAllAsRead(ctx context.Context, recipientID uuid.UUID) error
	MarkAsRead(ctx context.Context, arg MarkAsReadParams) error
}

var _ Querier = (*Queries)(nil)
